config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :artists , only: [ :index , :show ,:destroy , :new, :create] do

    resources :songs , only: [:destroy, :create]
  end

  namespace :api do
      resources :artists , only: [ :index , :show ,:destroy , :new, :create] do

      resources :songs , only: [:destroy, :create]
    end
  end
  
  root to: 'artists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  validates :name, presence: true

  has_many :songs , dependent: :destroy
  has_many :photos ,dependent: :destroy
  #accepts_nested_attributes_for :songs , allow_destroy: true

  def self.order_by_name_asc
    order(name: :asc)
  end

  def self.order_by_name_desc
    order(name: :desc)
  end

  def self.order_by_date_asc
    order(created_at: :asc)
  end

  def self.order_by_date_desc
    order(created_at: :desc)
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :artist 
  mount_uploader :image, ImageUploader
end

app/models/song.rb
class Song < ApplicationRecord
  validates :title, presence: true

  belongs_to :artist
end

app/controllers/api/songs_controller.rb
class Api::SongsController < ApplicationController

  skip_before_action :verify_authenticity_token

  def create

       @artist = Artist.find(params[:artist_id])

       @new_song = @artist.songs.new(song_params)


       if @new_song.save
         render status: 201, json: {
           message: "song successfully created",
           song: @new_song
         }.to_json
       else
         render status: 422, json: {
           errors: @new_song.errors
         }.to_json
       end

  end

  def destroy

    if params[:id] != 'delete_all'

      song = Song.find(params[:id])
      song.destroy

      render status: 200, json: {
        message: "song successfully deleted"
      }.to_json
    else
      @artist = Artist.find(params[:artist_id])
      @artist.songs.destroy_all

      render status: 200, json: {
        message: "all songs form artist successfully deleted"
      }.to_json
    end

  end
  def song_params
    params
      .require(:song)
      .permit(
        :title
      )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :destroy]

   IMAGE_NOT_FOUND = 'http://res.cloudinary.com/renatos/image/upload/v1517140901/imagenotfound_bytgea.jpg'

  def index

    @image_not_found = IMAGE_NOT_FOUND

    case params['order_by']
    when 'name_asc'
      @order_by_name = 'name_desc'
      @order_by_date = 'date_asc'
      @artists = Artist.order_by_name_asc
      @order_text_by_name = 'order names desc'
      @order_text_by_date = 'order dates desc'
    when 'name_desc'
      @order_by_name = 'name_asc'
      @order_by_date = 'date_asc'
      @artists = Artist.order_by_name_desc
      @order_text_by_name = 'order names asc'
      @order_text_by_date = 'order dates desc'
    when 'date_asc'
      @order_by_date = 'date_desc'
      @order_by_name = 'name_asc'
      @artists = Artist.order_by_date_asc
      @order_text_by_date = 'order dates desc'
      @order_text_by_name = 'order names asc'
    when 'date_desc'
      @order_by_date = 'date_asc'
      @order_by_name = 'name_asc'
      @artists = Artist.order_by_date_desc
      @order_text_by_date = 'order dates asc'
      @order_text_by_name = 'order names asc'
    else
      @order_by_name = 'name_desc'
      @order_by_date = 'date_asc'
      @order_text_by_name = 'order names desc'
      @order_text_by_date = 'order dates asc'
      @artists = Artist.order_by_name_asc
    end


  end

  def show
    @image_not_found = IMAGE_NOT_FOUND
    #@songs = @artist.songs.new
    #@songs = @artist.songs
    @image = @artist.photos.first ? @artist.photos.first.image.thumbnail : @image_not_found
  end

  def new
    @artist_item = Artist.new

  end

  def create

    #@artists = Artist.all

    @artist_item = Artist.new( artist_params )

    if @artist_item.save

      image_params.each do |image|
        @artist_item.photos.create(image: image)
      end
      redirect_to artists_path,  notice: "artist successfully created"
    else
      redirect_to artists_path , notice: "there was a problem saving the artist"
    end

  end

  def destroy
    @artist.destroy
    redirect_to artists_path
  end

  private

  def image_params
    params[:images].present? ? params.require(:images) : []
  end

  def set_artist
    @artist= Artist.find(params[:id])
  end

  def artist_params
   params
     .require(:artist)
     .permit(
       :name , songs_attributes: [ :title ]
     )
 end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create

    @artist = Artist.find(params[:artist_id])

    @new_song = @artist.songs.new(song_params)

    respond_to do |format|
        if @new_song.save
           format.json { render :show, status: :created, location: @artist }
           format.html { redirect_to artist_path(params[:artist_id]), notice: 'song successfully created' }
        else
           format.html { redirect_to artist_path(params[:artist_id]), notice: 'there was a problem saving the song' }
           format.json { render json: @artist.errors, status: :unprocessable_entity }
        end
    end
  end


  def destroy
    @song = Song.find(params[:id])

    @song.destroy

    redirect_to artist_path(params[:artist_id])
  end

  private

  def song_params
    params
      .require(:song)
      .permit(
        :title
      )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_for @artist_item, html: { multipart: true } do |f| %>

<h1>new artist</h1>

<div class="row">
<div class="col-xs-3">
<label>Name :</label>
</div>
<div class="col-xs-3">
<%= f.text_field :name, placeholder: "insert name" %></div>
</div>

<div class="row">
<div class="col-xs-3">
<label>Bio :</label>
</div>
<div class="col-xs-3">
<%= f.text_area :bio, placeholder: "insert bio" %></div></div>

Upload Photo
<%= file_field_tag "images[]", type: :file, multiple: true %>

<%= f.submit "create new artist" %>

<% end %>


<% if @photos %>
<% @photos.each do |photo| %>

  <%= image_tag photo.image %>

<% end %>
<% end %>

app/views/artists/index.html.erb
<header>
   <h1>music box</h1>
</header>
<div class="container">
<div>
<%= link_to @order_text_by_name , artists_path(order_by: @order_by_name) %> |
<%= link_to @order_text_by_date , artists_path(order_by: @order_by_date) %>
</div>

<div>

</div>
<% @artists.each do |artist| %>


  <article class="artist-article col-xs-12 col-sm-4">
        <h3><%= artist.name %></h3>
        <div class="thumbnail" style="background: url(<%= artist.photos.first ? artist.photos.first.image : @image_not_found %>) no-repeat center center ; background-size : cover"></div>


        <p><%= truncate(artist.bio, :length => 100, :omission => '...') %></p>


        <%= link_to artist.name , artist_path(artist), class: "btn btn-primary btn-xs" %>
      </article>
<% end %>
</div>

app/views/artists/new.html.erb
<%= notice %>


<%= render 'form' %>

app/views/artists/show.html.erb
<header>
  <h1><%= @artist.name %></h1>
</header>

<div class="container artist-show">

  <div class="col-xs-5">
    <div class="row">

        <%= image_tag @image  %>

    </div>

    <div class="row">
      <%= link_to "delete artist", artist_path(@artist.id), method: :delete, data: { confirm: "Are you sure you want to delete #{@artist.name}?" } %>
    </div>

    <div class="row">

      <form id="new_song">
        <label>Title :</label>
        <input id="hidden"  type="hidden" value="<%= @artist.id %>" />
        <input id="title" name="title" placeholder="Enter title" type="text" />
        <input type="submit" class="btn btn-primary btn-xs" value="save song">
      </form>


  </div>

</div>
<div class="col-xs-7">
  <button data-artist-id="<%= @artist.id  %>" id="delete_all_songs" class="btn btn-primary btn-xs">delete all songs</button>

<div id="song-list" >

  <% @artist.songs.each do |song| %>

    <div class="row">
      <div class="col-xs-7">
        <%= song.title %>
      </div>
      <div class="col-xs-5">
        <button data-artist-id="<%= @artist.id  %>" data-song-id="<%= song.id  %>" type="button" class="delete-song btn btn-primary btn-xs"><span class="oi oi-trash"></span></button>
      </div>
    </div>

  <% end %>

</div>
</div>
<%= notice %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

      <%= yield %>
  
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar">
  <div class="container">
    <ul class="navbar-block">
    <li><%= link_to 'HOME' , artists_path%></li>

    <li><%= link_to 'new artist' , new_artist_path %></li>
  </ul>
  </div>
</nav>